src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @Assert\NotBlank()
     * @Assert\Regex("/\+7\(\d{3}\)[0-9-]+$/")
     * @ORM\Column(type="string", length=50)
     */
    private $phone;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=255)
     */
    private $education;

    /**
     * @ORM\Column(type="boolean")
     */
    private $confirmedRule;

    /**
     * @ORM\Column(type="smallint")
     */
    private $score = 0;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSurname(): ?string
    {
        return $this->surname;
    }

    /**
     * @param string $surname
     * @return $this
     */
    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPhone(): ?string
    {
        return $this->phone;
    }

    /**
     * @param string $phone
     * @return $this
     */
    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string $email
     * @return $this
     */
    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getEducation(): ?string
    {
        return $this->education;
    }

    /**
     * @param string $education
     * @return $this
     */
    public function setEducation(string $education): self
    {
        $this->education = $education;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getConfirmedRule(): ?bool
    {
        return $this->confirmedRule;
    }

    /**
     * @return string
     */
    public function getConfirmedRuleText(): string
    {
        return $this->confirmedRule ? 'Да' : 'Нет';
    }

    /**
     * @param bool $confirmedRule
     * @return $this
     */
    public function setConfirmedRule(bool $confirmedRule): self
    {
        $this->confirmedRule = $confirmedRule;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getScore(): ?int
    {
        return $this->score;
    }

    /**
     * @param int $score
     * @return $this
     */
    public function setScore(int $score): self
    {
        $this->score = $score;

        return $this;
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use App\Enums\EducationsType;
use ReflectionClass;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class ClientType
 * @package App\Form
 */
class ClientType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('surname', TextType::class)
            ->add('phone', TelType::class)
            ->add('email', EmailType::class)
            ->add('education', ChoiceType::class, [
                'choices' => (new ReflectionClass(EducationsType::class))->getConstants(),
            ])
            ->add('confirmedRule', CheckboxType::class, [
                'required' => false
            ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Service\ClientService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ClientController
 * @package App\Controller
 */
class ClientController extends AbstractController
{

    /**
     * @Route("/client/{client}", name="client")
     * @param Client|null $client
     * @return Response
     */
    public function client(Client $client = null): Response
    {
        return $this->render('client/showClient.html.twig', [
            'client' => $client
        ]);
    }

    /**
     * @Route("/edit/{client}", name="editClient")
     * @param Request $request
     * @param ClientService $clientService
     * @param Client|null $client
     * @return Response
     */
    public function edit(Request $request, ClientService $clientService, Client $client = null): Response
    {
        $isCreate = !$client;
        if ($isCreate) {
            $client = new Client();
        }

        $form = $this->createForm(ClientType::class, $client);
        $form->add($isCreate ? 'create' : 'save', SubmitType::class);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $clientService->editClient($form->getData(), $isCreate);

            return $this->redirectToRoute('client', [
                'client' => $client->getId()
            ]);
        }

        return $this->render('client/index.html.twig', [
            'isCreate' => $isCreate,
            'client' => $client,
            'form' => $form->createView()
        ]);
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\ClientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="index")
     * @param Request $request
     * @param ClientRepository $clientRepository
     * @return Response
     */
    public function index(Request $request, ClientRepository $clientRepository): Response
    {
        $page = max(0, $request->query->getInt('page', 0) - 1);
        $paginator = $clientRepository->getClientPaginator($page);
        $pageCount = ceil($paginator->count() / ClientRepository::PAGINATOR_PER_PAGE);

        return $this->render('main/index.html.twig', [
            'clients' => $paginator,
            'currentPage' => $page + 1,
            'pageCount' => $pageCount
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        {% endblock %}


    </head>
    <body>
        {% block body %}{% endblock %}
    </body>

    {% block javascripts %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <script src="https://unpkg.com/imask"></script>
        <script>
            const element = document.getElementById('client_phone');
            if (element !== null) {
                const maskOptions = {
                    mask: '+{7}(000)000-00-00',
                    lazy: false
                };
                const mask = IMask(element, maskOptions);
            }

        </script>
    {% endblock %}
</html>

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ClientController!{% endblock %}

{% block body %}

    <div class="container">
        {% if isCreate %}
            <h2>Создание клиента <a class="btn btn-primary" href="{{ path('index') }}" role="button">Отмена</a></h2>
        {% else %}
            <h2>Редактирование клиента <a class="btn btn-primary" href="{{ path('client', {'client': client.id}) }}" role="button">Отмена</a></h2>
        {% endif %}
        {{ form(form) }}
    </div>
{% endblock %}

templates/client/showClient.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <a class="btn btn-primary" href="{{ path('index') }}" role="button">Назад</a>

        {% if client %}
            <h2>Информация о клиенте <a class="btn btn-primary" href="{{ path('editClient', {'client': client.id}) }}"
                                        role="button">Редактировать</a></h2>
            <ul class="clientInfo">
                <li>Имя: <span>{{ client.name }}</span></li>
                <li>Фамилия: <span>{{ client.surname }}</span></li>
                <li>Номер телефона: <span>{{ client.phone }}</span></li>
                <li>Почта: <span>{{ client.email }}</span></li>
                <li>Образование: <span>{{ client.education|trans }}</span></li>
                <li>Согласие на обработку данных: <span>{{ client.confirmedRuleText }}</span></li>
                <li>Балл: <span>{{ client.score }}</span></li>
            </ul>
        {% else %}
            <p>Клиент не найден</p>
        {% endif %}
    </div>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}

    <div class="container">
        <a class="btn btn-primary" href="{{ path('editClient', {'client': null}) }}" role="button">Добавить клиента</a>

        <table class="table">
            <thead>
            <tr>
                <th scope="col">Клиент</th>
                <th scope="col">Балл</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for client in clients %}
                <tr>
                    <td>{{ client.name }} {{ client.surname }}</td>
                    <td>{{ client.score }}</td>
                    <td><a class="btn btn-primary" href="{{ path('client', {'client': client.id}) }}" role="button">Показать</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <nav aria-label="navigation">
            <ul class="pagination">
                <li class="page-item {{ currentPage == 1 ? 'disabled':'' }}">
                    <a class="page-link" href="{{ path('index', { page: currentPage-1 }) }}">Previous</a>
                </li>
                {% for i in 1..pageCount %}
                    <li class="page-item {{ currentPage == loop.index ? 'active':'' }}" ><a class="page-link" href="{{ path('index', { page: loop.index }) }}">{{ loop.index }}</a></li>
                {% endfor %}
                <li class="page-item {{ currentPage == pageCount ? 'disabled':'' }}">
                    <a class="page-link" href="{{ path('index', { page: currentPage+1 }) }}">Next</a>
                </li>
            </ul>
        </nav>

        <ul>

        </ul>
    </div>
{% endblock %}